# Generated by Django 6.0.5 on 2026-08-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Objetivo Estratégico',
                'verbose_name_plural': 'Objetivos Estratégicos',
            },
        ),
    ]
