# Generated by Django 6.0.5 on 2026-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('prazo_inicio', models.DateField()),
                ('prazo_fim', models.DateField()),
                ('custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJAMENTO', max_length=20)),
            ],
            options={
                'verbose_name': 'Ação Realizada',
                'verbose_name_plural': 'Ações Realizadas',
            },
        ),
        migrations.CreateModel(
            name='IniciativaEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('percentual_evolucao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Iniciativa Estratégica',
                'verbose_name_plural': 'Iniciativas Estratégicas',
            },
        ),
    ]
