# Generated by Django 6.0.5 on 2026-06-11 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iniciativasEstrategicas', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativaestrategica',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iniciativas_estrategicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iniciativaestrategica',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iniciativas_estrategicas', to='unidades.unidade'),
        ),
        migrations.AddField(
            model_name='acaorealizada',
            name='fk_iniciativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_realizadas', to='iniciativasEstrategicas.iniciativaestrategica'),
        ),
    ]
