# Generated by Django 6.0.5 on 2026-06-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iniciativasEstrategicas', '0001_initial'),
        ('projetosEstrategicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativaestrategica',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iniciativas_estrategicas', to='projetosEstrategicos.projetoestrategico'),
        ),
    ]
