# Generated by Django 6.0.5 on 2026-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucaoOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evolução Orçamentaria',
                'verbose_name_plural': 'Evoluções Orçamentarias',
            },
        ),
        migrations.CreateModel(
            name='EvolucaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizacao', models.TextField()),
                ('proximo_passo', models.TextField()),
            ],
            options={
                'verbose_name': 'Evolução do Projeto',
                'verbose_name_plural': 'Evoluções do Projeto',
            },
        ),
        migrations.CreateModel(
            name='ProjetoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tempo_estimado', models.CharField(max_length=100)),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('percentual_progresso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('acoes_previstas', models.TextField()),
            ],
            options={
                'verbose_name': 'Projeto Estratégico',
                'verbose_name_plural': 'Projetos Estratégicos',
            },
        ),
    ]
