# Generated by Django 6.0.5 on 2026-06-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetosEstrategicos', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoestrategico',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_estrategicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetoestrategico',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_estrategicos', to='unidades.unidade'),
        ),
        migrations.AddField(
            model_name='evolucaoprojeto',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evolucoes', to='projetosEstrategicos.projetoestrategico'),
        ),
        migrations.AddField(
            model_name='evolucaoorcamentaria',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EvolucoesOrcamentarias', to='projetosEstrategicos.projetoestrategico'),
        ),
    ]
